PDFWriter/PDFParser.cpp
check if there is PDFWitespaces between xRef sections.
=> In ParseXrefFromXrefTable method

PDFWriter/TIFFImageHandler.cpp, PDFWriter/TIFFImageHandler.h
This code should allow both 3.9.5 and 4.0.x branch of tiff to be used.
Macro definitions to override default behavior on custom compile.
Tests TIFFImageTest fail with tiff 4.0.6, because of heap overflow when a tiff's strips have different sizes (ycbcr-cat.tif).
=> compatibility issues with libtiff 4.0.x

PDFWriter/DocumentContext.h, PDFWriter/EncryptionOptions.cpp, PDFWriter/EncryptionOptions.h, PDFWriter/PDFDocumentHandler.cpp, PDFWriter/PDFObject.cpp, PDFWriter/PDFObject.h, PDFWriter/PDFParser.cpp, PDFWriter/PDFParser.h, PDFWriter/PDFParsingOptions.cpp, PDFWriter/PDFParsingOptions.h, PDFWriter/PDFWriter.cpp, PDFWriter/PDFWriter.h, PDFWriter/ParsedPrimitiveHelper.cpp, PDFWriter/TIFFImageHandler.cpp, PDFWriter/TIFFImageHandler.h, PDFWriter/TiffUsageParameters.cpp, PDFWriter/TiffUsageParameters.h, PDFWriter/Trace.cpp, PDFWriter/Trace.h, PDFWriterTestPlayground/PDFParserTest.cpp, PDFWriterTestPlayground/RecryptPDF.cpp
Dll's don't export the static member properties, and there will be undefined symbols at linking time.
Static member properties are converted to functions.
=> Hummus dll

PDFWriter/CMYKRGBColor.cpp, PDFWriter/CMYKRGBColor.h, PDFWriter/InfoDictionary.cpp, PDFWriter/PDFDate.cpp, PDFWriter/PDFObjectParser.cpp, PDFWriter/PDFTextString.cpp, PDFWriter/PDFTextString.h, PDFWriterTestPlayground/CMakeLists.txt, PDFWriterTestPlayground/PDFDateTest.cpp, PDFWriterTestPlayground/PDFObjectParserTest.cpp, PDFWriterTestPlayground/PDFObjectParserTest.h
PDFDate and PDFObjectParser fixes.
For PDFDate: I can't test mac. In vs2013 the gcc code works, no need to ifdef for msvc. Maybe also works for mac.
=> Automated tests

PDFWriter/InputAscii85DecodeStream.cpp
Consecutive sets of 5 '0' bytes represented by 'z' weren't actually getting added to output.
=> Bug fix to Ascii85 decoder

PDFWriter/PDFParser.cpp
Old Oracle Reports generates PDFs with indirect Kids object.
E.g.
3 0 obj
<<
/Type /Pages
/Kids 4 0 R
/Count 5 0 R
>>
endobj
4 0 obj
[ 6 0 R 18 0 R 21 0 R 24 0 R ]
endobj
=> handle indirect Kids object

PDFWriter/PDFUsedFont.cpp
The CalculateTextMetrics function returned whole numbers as results instead of doubles.
For instance:
`auto dimensions = arial.CalculateTextDimensions("€", 12);
std::cout << dimensions.width << std::endl;`
Would return 6 instead of the correct 6.6.. which makes right aligning difficult.
=> Fixed CalculateTextMetrics integer math to double math

PDFWriter/DocumentContext.cpp, PDFWriter/PDFWriter.cpp, PDFWriterTestPlayground/PNGImageTest.cpp
Hi, I am testing PDF-Writer with PDFHUMMUS_NO_PNG defined, and troubled with compiler errors.
I found some "#ifndef PDFHUMMUS_NO_PNG" scopes are wrong or missing.
=> Fix "#ifndef PDFHUMMUS_NO_PNG" scopes

PDFWriter/CFFFileInput.h, PDFWriter/PDFDictionary.h, PDFWriter/Type1ToType2Converter.h
Currently, PDF-Writer doesn't compile with a C++17 compiler (like VS2017 with option /std:c++17), because it uses std::binary_function, which is removed by C++17.
std::binary_function is not needed here, so my mods remove it.
Best Regards,
Mathias
=> remove dependence on std::binary_function to allow compilation as C++17

PDFWriter/DecryptionHelper.cpp
DecryptionHelper::DecryptString leaked memory (according to valgrind). I made a fix, using auto_ptr. Also DecryptionHelper::OnObjectEnd caused access violation if inObject was null somehow.
=> Minor issues with DecryptionHelper

PDFWriter/PDFModifiedPage.cpp
PDFModifiedPage leaks some memory and this becomes a problem when modifying too many pages with a single process. This PR deletes the objects that remain in memory when destroying PDFModifiedPage.
=> Plug memory leaks in PDFModifiedPage

.gitignore, FreeType/CMakeLists.txt, LibAesgm/CMakeLists.txt, LibJpeg/CMakeLists.txt, LibPng/CMakeLists.txt, LibTiff/CMakeLists.txt, PDFWriter/CMakeLists.txt, ZLib/CMakeLists.txt
add optional target PDFWriterAll (when configuring with CREATE_PDFWRITER_ALL=TRUE). This will create a single lib with PDFWriter and all it's dependencies that can be used as an alternative input for a project.
it's a step towards a potential [emscripten](https://github.com/kripken/emscripten) compilation.
=> create a single lib target for PDFWriter and deps, called PDFWriterAll

PDFWriter/PDFModifiedPage.cpp
Hello ! 
After investigating the leak from https://github.com/galkahana/HummusJS/issues/259 I found that in some case a stream is created and then another one is allocated without freeing the previous one.
=> Free memory for created stream to avoid memory leak.

PDFWriter/InputStreamSkipperStream.cpp, PDFWriter/PDFParser.cpp
Fix for https://github.com/galkahana/PDF-Writer/issues/167 in case it helps anyone else with PDF-Writer / hummus crashes on HP Exstream pdf files where they're using an "Fl" alias instead of "FlateDecode".
All regular tests passing. (61 tests succeeded, 0 tests failed.)
=> Add Fl alias and stream null check to avoid crashes

CMakeLists.txt, FreeType/CMakeLists.txt, LibAesgm/CMakeLists.txt, LibJpeg/CMakeLists.txt, LibPng/CMakeLists.txt, LibTiff/CMakeLists.txt, PDFWriterTestPlayground/CMakeLists.txt, ZLib/CMakeLists.txt
got a new m1. hummus compiling throws link errors for libpng neon. providing same treatment as was done for android  support - disabling neon on arm.
also...got warnings for coming deprecation of any version of cmake prior to 2.8.10...so updated cmake files to properly indicate that version as the new supported min.
=> m1 support

PDFWriter/PDFParser.cpp, PDFWriter/PDFParser.h
- per @julianhille  suggestion [here](https://github.com/galkahana/PDF-Writer/pull/186#discussion_r1040519253) the xref size validation check is moved to `ExtendXrefToSize`. This method is shared by callers performing the check size as part of their code...better to avoid forgetting to check there by moving the check to the shared code. plus we reuse the share (look....it's less code :))
=> xref parsing corrections

PDFWriter/JPEGImageParser.cpp
There is a small typo in PDFWriter/JPEGImageParser.cpp.
Should read `secondary` rather than `seconary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, seconary -> secondary

CMakeLists.txt, PDFWriter/InputFlateDecodeStream.cpp, PDFWriter/PDFParserTokenizer.cpp
running fuzz tests on my mac for the text extraction project was failing erratically for one of the files (526).
also recreating a decompressed version didn't work.
traced the first problem to a too permissive hex string parsing which caused over-reads.
and the second problem to a too restrictive zip decoding issue where end of stream error canceled the whole stream reading. which is a shame cause it could parse something worthwhile till then, like in this case.
=> fix: harsher hex string parsing to avoid more dire parsing errors

PDFWriter/CFFDescendentFontWriter.cpp, PDFWriter/DescendentFontWriter.cpp, PDFWriter/DescendentFontWriter.h, PDFWriter/TrueTypeDescendentFontWriter.cpp, PDFWriterTesting/CIDSetWritingCFF.cpp, PDFWriterTesting/CIDSetWritingTrueType.cpp, PDFWriterTesting/CMakeLists.txt
turns out the CIDSet implementation was wrong for either true type or open type.
it shouldn't match the glyphs that are used, but rather how they are represented in the font program
so instead of marking each bit per the glyph id is should:
- for true type mark 0 till max glyph including with all the glyphs between them also as i map them to blanks
- for open type the font program just uses 0...glyphs count as the cid indexes
so the final implementation is actually much simpler than it was....and also actually correct
=> bug: wrong CIDSet implementation

PDFWriter/PDFParser.cpp, PDFWriter/PDFParser.h
a  more consistent code in CreateFilterForStream can avoid dual deletion of stream in case of error, and avoid a CVE.
=> correction to uaf1 cve

PDFWriter/TIFFImageHandler.h
I met compilation error on gcc 13. (work fine on gcc 12)
```
In file included from PDFWriter/DocumentContext.h:29,
from PDFWriter/PDFWriter.h:30,
from test_package.cpp:2:
/PDFWriter/TIFFImageHandler.h:142:9: error: ‘uint64_t’ does not name a type
142 | typedef uint64_t tsize_t_compat;
|         ^~~~~~~~
PDFWriter/TIFFImageHandler.h:83:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
82 | #include <list>
+++ |+#include <cstdint>
83 | #include <utility>
```
As compiler suggested, this patch include cstdint.
Please merge it if possible.
=> include cstdint to fix compilation error on gcc 13

PDFWriter/TIFFImageHandler.h
im using stdint.h instead of cstdint for allowing the same effect of compiling successfully on gcc, while allowing a bit more potential projects, those that are c99 but dont use c+11.
=> feat: use stdint instead of cstdint, conforming to c99 instead of c+11

.gitattributes, CMakeLists.txt
To resolve #243, this MR use .gitattributes to exclude PDFWriterTesting from archives.
This will mean no future packages of PDFWriter will include PDFWriterTesting, allowing for a highly diminished and effective downloads for users of PDFWriter.
This allows continuing adding test cases to PDFWriter without increasing the users downloaded package.
=> exclude pdfwriter testing from git archives

.gitignore, PDFWriterTesting/TextUsageBugs.cpp
`NotoSerifCJKkr-Regular.otf` is a subset of `NotoSerifCJK-Regular.ttc`, use ttc and remove otf to reduce the size of the git repo.
=> chore: use NotoSerifCJK-Regular.ttc instead of NotoSerifCJKkr-Regular.otf

PDFWriter/CharStringType1Interpreter.cpp, PDFWriter/CharStringType1Interpreter.h, PDFWriter/CharStringType1Tracer.cpp, PDFWriter/CharStringType2Flattener.cpp, PDFWriter/CharStringType2Flattener.h, PDFWriter/CharStringType2Interpreter.cpp, PDFWriter/CharStringType2Interpreter.h, PDFWriter/CharStringType2Tracer.cpp, PDFWriter/CharStringType2Tracer.h, PDFWriter/IType2InterpreterImplementation.h, PDFWriter/Type1Input.cpp, PDFWriter/Type1ToType2Converter.cpp, PDFWriter/Type1ToType2Converter.h
Following a recent look into type2 fonts implementation in the library i realized there's not much there by way of securing the usage of type2 and type1 fonts. they are interpreted in order to create relevant representations in and outcome pdf, but there's no checks into the validity of glyph operators within glyphs charstrings.
This can be be problematic if you are creating a PDF that includes a faulty (or even malicious) font. normally this would not be the case...you are using fonts that you know, but if you are a general purpose mechanism allowing users to submit their fonts, there's a bit of a chance that an erring font might find it's way into your mechanism.
then you would like protections from simple things like a glyph subroutine calling another one and it in turn calling back …
=> Galk.interpreters.limits implementation

PDFWriter/AbstractContentContext.cpp, PDFWriterTesting/CMakeLists.txt, PDFWriterTesting/UnicodeTextUsage.cpp
To fix the effect described in https://github.com/galkahana/PDF-Writer/issues/253, drop the initial encoding to hex and just do the CID code writing.
A bug corrected for Tj long time ago didn't get to TJ.
=> avoiding dual hex encoding for TJ command

PDFWriter/TrueTypeDescendentFontWriter.cpp, PDFWriter/TrueTypeEmbeddedFontWriter.cpp
see issue #255 .
adding checks that glyph ids are not illegal. glyph id can come from user input or some error, so might cause unexpected issues. 
in descendent font checking against max possible value which is 0xffff -1, later when there's more information about the font checking against max glyph id which is glyph count - 1. glyph count in turn is unsigned short, and so this check includes the oxffff -1 range.
=> adding safeguards so input of oxffff glyph id isn't problematic

PDFWriter/AbstractWrittenFont.cpp, PDFWriter/AbstractWrittenFont.h, PDFWriter/FreeTypeFaceWrapper.cpp, PDFWriter/IWrittenFont.h, PDFWriter/PDFUsedFont.cpp, PDFWriter/WrittenFontCFF.cpp, PDFWriter/WrittenFontCFF.h, PDFWriter/WrittenFontTrueType.cpp, PDFWriter/WrittenFontTrueType.h, PDFWriterTesting/CMakeLists.txt, PDFWriterTesting/TrueTypeAnsiWriteBug.cpp
To resolve #255.
In order to use winansiencoding (or in other words...non cid encoding) for true type fonts, the embedded font program must contain a method to translate the winansiencoding glyph names to glyph ids. For this to happen, there should be either 3,1 cmap encoding existing (win unicode bmp) or 1,0 cmap (mac roman). helveticaneue, for instance, does not have this table and so the library should not attempt to build a winansiencoding representation, but go straight to cid. arial.ttf does have the right cmaps and so can use it.
=> bug: not all true types can use winansiencoding. need to check cmaps

PDFWriter/PDFParser.cpp
Seems to be a typo, otherwise this can lead to the following null pointer when /First does not exist.
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555789696 in PDFInteger::GetValue (this=0x0) at PDF-Writer/PDFWriter/PDFInteger.cpp:34
34		return mValue;
#0  0x0000555555789696 in PDFInteger::GetValue (this=0x0)
at PDF-Writer/PDFWriter/PDFInteger.cpp:34
#1  0x000055555574de05 in PDFParser::ParseExistingInDirectStreamObject (this=0x7ffff5d09060, inObjectId=10)
at PDF-Writer/PDFWriter/PDFParser.cpp:1762
#2  0x000055555574ad36 in PDFParser::ParseNewObject (this=0x7ffff5d09060, inObjectId=10)
at PDF-Writer/PDFWriter/PDFParser.cpp:730
#3  0x000055555573fed6 in PDFParser::ParsePagesObjectIDs (this=0x7ffff5d09060)
at PDF-Writer/PDFWriter/PDFParser.cpp:848
#4  0x000055555573b6a1 …
```
=> bug: Fix possible null pointer when /First does not exist

LibTiff/binding.gyp, LibTiff/tif_config.h
update pdfwriter per node setup for ia32 supporting config for libtiff
=> conf: setup to allow building libtiff to support ia32 envs in node

PDFWriter/DocumentContext.cpp, PDFWriter/DocumentContext.h, PDFWriter/IndirectObjectsReferenceRegistry.cpp, PDFWriter/IndirectObjectsReferenceRegistry.h, PDFWriter/PDFWriter.cpp, PDFWriter/PDFWriter.h, PDFWriterTesting/CMakeLists.txt, PDFWriterTesting/XrefStreamsTest.cpp
Enable using Xref streams for regular PDF files (and not just modified files, as it was). To do this provide StartPDF/StartPDFForStream with PDFCreationSettings which inWriteXrefAsXrefStream is true. You should also aim for PDFVersion of 1.5 or higher (the last one is more for the sake of readers as xref streams are a 1.5 feature (or higher).
See XrefStreamsTest.cpp for an example.
What this allows is to lift the limit of 10gbs for file size imposed by regular xrefs that use 10 decimal digits to describe file offset. You can now use the full long long kind of size (~8 EBs or ~8K TBs).
=> feat: allow asking for using xref streams, which opens the option to build very large files

PDFWriter/ByteList.cpp, PDFWriter/ByteList.h, PDFWriter/InputAESDecodeStream.h, PDFWriter/InputRC4XcodeStream.h, PDFWriter/MD5Generator.h, PDFWriter/OutputAESEncodeStream.h, PDFWriter/OutputRC4XcodeStream.h, PDFWriter/RC4.h
It is really inefficient to have std::list<IOBasicTypes::Byte> has huge overhead as each single Byte would be
struct Node {
Node* prev;    // 8 B
Node* next;    // 8 B
byte  value;   // 1 B
// padding/alignment → ~24 B total
};
then there is cache unfriendly traversal, allocation cost...
Alternatives could be std::vector<IOBasicTypes::Byte> or std::deque<byte>, but std::basic_string seems a better fit as it already has substr, append, and similar operations.
After this change, maybe ByteList isn't the best name anymore, but I went for minimal changes
=> refactor: replace ByteList type from std::list to std::basic_string
